# Generated by Django 4.2.29 on 2026-04-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydration',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='routinelog',
            name='date',
            field=models.DateField(),
        ),
    ]
