# Generated by Django 4.2.29 on 2026-04-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0002_alter_hydration_date_alter_routinelog_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('EARNING', 'Ganho'), ('FIXED_EXPENSE', 'Gasto Fixo'), ('DAILY_EXPENSE', 'Gasto Diário')], max_length=20)),
                ('date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
