# Generated by Django 4.2.29 on 2026-04-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0003_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='routinelog',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
