# Generated by Django 4.2.29 on 2026-04-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0004_routinelog_notes_transaction_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='icon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='icon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
