# Generated by Django 4.2.29 on 2026-04-12 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0008_travelplan_travelcomboitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelItineraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('BREAKFAST', 'Cafe da manha'), ('AFTERNOON', 'Tarde'), ('TOUR', 'Passeio'), ('LUNCH', 'Almoco'), ('DINNER', 'Jantar'), ('DESSERT', 'Sobremesa'), ('OTHER', 'Outros')], max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('travel_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_items', to='routine_app.travelplan')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
