# Generated by Django 4.2.29 on 2026-04-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0012_travel_values_expected_real'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelitineraryitem',
            name='item_type',
            field=models.CharField(choices=[('BREAKFAST', 'Cafe da manha'), ('AFTERNOON', 'Cafe da tarde'), ('TOUR', 'Passeio'), ('LUNCH', 'Almoco'), ('DINNER', 'Jantar'), ('DESSERT', 'Sobremesa'), ('OTHER', 'Outros')], max_length=30),
        ),
    ]
