# Generated by Django 4.2.29 on 2026-04-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0013_alter_travelitineraryitem_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelaccommodationitem',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelaccommodationitem',
            name='event_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelitineraryitem',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelitineraryitem',
            name='event_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
