# Generated by Django 4.2.29 on 2026-04-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0014_travel_dates_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelaccommodationitem',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='travelitineraryitem',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
