# Generated by Django 4.2.29 on 2026-04-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0015_travel_item_completion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelitineraryitem',
            name='item_type',
            field=models.CharField(choices=[('BREAKFAST', 'Cafe da manha'), ('AFTERNOON', 'Cafe da tarde'), ('TOUR', 'Ponto turistico'), ('SHOP', 'Lojas'), ('LUNCH', 'Almoco'), ('DINNER', 'Jantar'), ('DESSERT', 'Sobremesa'), ('OTHER', 'Outros')], max_length=30),
        ),
    ]
