# Generated by Django 4.2.29 on 2026-04-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0016_alter_travelitineraryitem_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelaccommodationitem',
            name='checkin_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelaccommodationitem',
            name='checkout_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelaccommodationitem',
            name='entry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelaccommodationitem',
            name='exit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
