# Generated by Django 4.2.30 on 2026-04-28 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0020_desafioitem_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routinelog',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='routinelog',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
