# Generated by Django 4.2.30 on 2026-04-28 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0021_alter_routinelog_options_routinelog_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travelaccommodationitem',
            options={'ordering': ['entry_date', 'order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='travelitineraryitem',
            options={'ordering': ['event_date', 'order', 'id']},
        ),
        migrations.AddField(
            model_name='travelaccommodationitem',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='travelitineraryitem',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
