# Generated by Django 4.2.30 on 2026-05-05 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_app', '0022_alter_travelaccommodationitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydration',
            name='goal',
            field=models.IntegerField(default=3000),
        ),
    ]
