version: '3.8'

services:
  backend:
    build: ./backend
    container_name: rotina_backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: sh -c "python manage.py makemigrations routine_app && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  frontend:
    build: ./frontend
    container_name: rotina_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host
