FROM python:3.11-slim
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
WORKDIR /app
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt
COPY . /app/
CMD sh -c "python manage.py makemigrations routine_app && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
